name: Build, Test, and Deploy

on:
  push:
    branches:
      - main
      - master

env:
  PROJECT_VERSION: "1.0.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 17
          distribution: temurin

      - name: Cache
        uses: actions/cache@v4.1.2
        with:
          path: ~/.m2/repository
          key: libraries

      - name: Build le JAR
        run: mvn clean package -DskipTests
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"

      - name: Nenommer et sauvegarder JAR artefact
        run: mv target/*.jar target/helloworld-${{ env.PROJECT_VERSION }}.jar

      - name: Upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: helloworld-jar
          path: target/helloworld-${{ env.PROJECT_VERSION }}.jar
          
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: mvn test
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=~/.m2/repository"
        continue-on-error: true # Continuer même si les tests échouent

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build
      - tests
    steps:

      - name: Telecharger artefact
        uses: actions/download-artifact@v3
        with:
          name: helloworld-jar
          path: ./deployments

      - name: Simuler deploiement
        run: |
          echo "Déploiement de l'application..."
          ls ./deployments
          echo "Déploiement terminé avec succès de helloworld-${{ env.PROJECT_VERSION }}.jar"

